# Generated by Django 3.2.5 on 2021-11-04 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Projects',
        ),
    ]
